### ISSUE TITLE
fullscreen IE11

### ISSUE THREAD

**Issue by eliz82** [robnyman/robnyman.github.com#21]
regarding your problem of scrollable fullscreen with IE11 http://robnyman.github.io/fullscreen/index-high-content.html

see my solution https://stackoverflow.com/a/44482445/4481831

after that i don't think you need html:-ms-fullscreen { width: 100%; /* needed to center contents in IE */}

**Comment by robnyman** [comment]
Interesting! Many years since I put together this code. :-)
If you create a pull request with a working solution, I'd be happy to merge it.
