### ISSUE TITLE
Saving Audio files on Local Storage/Session Storage

### ISSUE THREAD

**Issue by Khondwani** [robnyman/robnyman.github.com#25]
Would it be possible to save data like audio files onto local storage or session storage?? and if yes how can that be achieved

**Comment by robnyman** [comment]
Interesting question! IndexedDB would be a better approach then, I think; I blogged about that many years in [https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/](https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/). Hope it helps as a starting inspiration!

**Comment by Khondwani** [comment]
Thank you so much!! I have another question if you don’t mind.. the online Converters the ones that convert an uploaded file from our computers to other data extensions. How do they store the file that has been uploaded with out having a database for users to login in and how is it secure cause I want to build an online converter where people upload data and as soon as they leave that page the data they uploaded is deleted and that’s why I was looking at session storage but it’s to small 

Sent from my iPhone 

> On 10 Apr 2018, at 09:46, Robert Nyman <notifications@github.com> wrote:
> 
> Interesting question! IndexedDB would be a better approach then, I think; I blogged about that many years in https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/. Hope it helps as a starting inspiration!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
This message and attachments are subject to a disclaimer. Please refer to 

http://www.it.up.ac.za/documentation/governance/disclaimer/ 
<http://www.it.up.ac.za/documentation/governance/disclaimer/> for full 
details.

**Comment by robnyman** [comment]
That one, I unfortunately don't know too much about. But in essence, using IndexedDB you should be able to have more storage size and keep it only for the session, and just make sure to delete it when the window/tab has been closed, or the user has navigated away.

**Comment by Khondwani** [comment]
Yet again thank you !!! 

Sent from my iPhone 

> On 10 Apr 2018, at 12:09, Robert Nyman <notifications@github.com> wrote:
> 
> That one, I unfortunately don't know too much about. But in essence, using IndexedDB you should be able to have more storage size and keep it only for the session, and just make sure to delete it when the window/tab has been closed, or the user has navigated away.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
This message and attachments are subject to a disclaimer. Please refer to 

http://www.it.up.ac.za/documentation/governance/disclaimer/ 
<http://www.it.up.ac.za/documentation/governance/disclaimer/> for full 
details.
